ignore:
  - data/*
  - logs/*
  - tests/*
  - tmp/*
  - __pycache__
  - .venv/*
  - "*_test.py"

refactor:
  skip: []

metrics:
  quality_threshold: 50.0

clone_detection:
  min_lines: 3
  min_duplicates: 2
  identical_clones_only: false

github:
  labels: []
  ignore_labels: [sourcery-ignore]
  request_review: author
  sourcery_branch: sourcery/{base_branch}
